<h1> Assignment – 4: Numerical Computation with NumPy</h1>

**Aim**: Numerical Computation with NumPy, Perform different computations using

**Theory**:

NumPy, short for Numerical Python, is the fundamental package for numerical computation in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. At its core, NumPy allows for efficient operations on large arrays of numerical data, which is crucial for scientific computing, data analysis, and machine learning. Its primary advantage comes from its ability to perform vectorized operations, reducing the need for explicit loops and significantly boosting execution speed compared to pure Python lists. This efficiency is further enhanced because many of NumPy's operations are implemented in C.

In [ ]:
import numpy as np

arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("2D Array:\n", arr_2d)

print("\nElement at index [1, 2]:", arr_2d[1, 2]) # Output: 60

print("\nSliced Sub-array:\n", arr_2d[0:2, 1:3])

arr = np.array([1, 2, 3, 4])
print("\nOriginal Array:", arr)
print("Square of Array:", np.square(arr))
print("Sum of elements:", np.sum(arr))
print("Mean value:", np.mean(arr))

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at index [1, 2]: 60

Sliced Sub-array:
 [[20 30]
 [50 60]]

Original Array: [1 2 3 4]
Square of Array: [ 1  4  9 16]
Sum of elements: 10
Mean value: 2.5


**1. Role of NumPy in Scientific Computing**

NumPy is a Python library used for scientific and numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to perform efficient operations on these arrays.

  1. Support for large, multi-dimensional arrays and matrices.

  2. A large collection of high-level mathematical functions to operate on these arrays.

  3. The foundational data structure used by almost all other data science libraries like Pandas, Scikit-learn, and Matplotlib.




<br>



<br>



**2. Why is NumPy faster than Pure Python?**

NumPy is significantly faster for numerical operations because:

  1. Vectorization: It performs operations on entire arrays at once without needing explicit for loops in Python.

  2. C-Implementation: Its core functions are written in C, which allows for highly optimized, low-level execution.

  3. Contiguous Memory: NumPy arrays are stored in a continuous block of memory, making access much faster than Python lists.


**3. Mathematical Operations in NumPy**

NumPy supports a wide range of operations:

  1. Arithmetic: Addition, subtraction, multiplication, division.

  2. Linear Algebra: Matrix multiplication, dot products, determinants, and inverses.

  3. Statistics: Mean, median, standard deviation, and variance.

  4. Trigonometry: Sine, cosine, tangent, etc.

**4. NumPy Basics & Operations**
NumPy Basics & Operations (in NumPy):

NumPy provides efficient ways to work with numerical data using arrays and supports a wide range of mathematical operations.

1. Array Creation:
NumPy allows creation of arrays from lists or built-in methods.
These arrays can be 1D, 2D, or multi-dimensional.

2. Types of Arrays:
* 1D arrays: single row or column of elements
* 2D arrays: rows and columns (like a matrix)
* Multi-dimensional arrays: used for complex data structures

3. Basic Operations:
Performs element-wise arithmetic operations such as addition, subtraction, multiplication, and division
Supports operations between two arrays of the same shape

4. Indexing and Slicing:
Allows accessing specific elements or a range of elements from an array.
Helps in extracting required portions of data

**5. NumPy Integration with Other Libraries:**

NumPy plays a central role in Python’s data science ecosystem and acts as the core “engine” for many important libraries.

1. Pandas: Uses NumPy arrays internally to store and manage data efficiently in DataFrames.

2. Matplotlib: Relies on NumPy arrays to handle numerical data for plotting graphs and charts.

3. Scikit-learn: Requires data in the form of NumPy arrays for training and testing machine learning models.

**Conclusion**:

In conclusion, NumPy is an indispensable library for anyone working with numerical data in Python. Its array object and optimized functions enable fast and efficient computations, making it a cornerstone for data science, scientific research, and engineering tasks. Understanding NumPy is key to leveraging the broader Python data ecosystem, as it underpins many other powerful libraries.